Failed to generate or share PDF. Please try agai
i get this error and also please fix the below code

Error: In HTML, whitespace text nodes cannot be a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <Presence present={true}>
      <Primitive.div data-state="active" data-orientation="horizontal" role="tabpanel" aria-labelledby="radix-«R8t..." ...>
        <div data-state="active" data-orientation="horizontal" role="tabpanel" aria-labelledby="radix-«R8t..." ...>
          <BillGenerator availableProducts={[...]}>
            <_c>
              <div ref={null} className="rounded-lg...">
                <_c2>
                <_c8 className="space-y-4">
                  <div ref={null} className="p-6 pt-0 s...">
                    <div>
                    <div>
                    <div className="rounded-md...">
                      <_c>
                        <div className="relative w...">
                          <table ref={null} className="w-full cap...">
                            <_c2>
                            <_c4>
                            <_c6>
                              <tfoot ref={null} className={"border-t..."}>
                                <_c8 className="bg-muted/5...">
>                                 <tr
>                                   ref={null}
>                                   className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-m..."
>                                 >
                                    <_c12>
                                    <_c12>
                                    <_c12>
>                                   {" "}
                ...
            ...

    at createUnhandledError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at completeWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9585:87)
    at runWithFiberInDEV (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at completeUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10233:23)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10170:28)
    at workLoopSync (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10060:40)
    at renderRootSync (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10043:13)
    at performWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:212)
    at performSyncWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10804:9)
    at flushSyncWorkAcrossRoots_impl (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10724:316)
    at processRootScheduleInMicrotask (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10744:9)
    at http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10815:158
    at tr (<anonymous>)
    at _c8 (http://localhost:9002/_next/static/chunks/src_components_a35a6627._.js:311:449)
    at BillGenerator (http://localhost:9002/_next/static/chunks/src_components_a35a6627._.js:2375:257)
    at Home (rsc://React/Server/C:%5CBill%20Management%20System%5CBill-Management-system%5C.next%5Cserver%5Cchunks%5Cssr%5C%5Broot%20of%20the%20server%5D__451b0374._.js?7:424:286)

this is first error

Error: In HTML, whitespace text nodes cannot be a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <RedirectErrorBoundary router={{...}}>
      <InnerLayoutRouter url="/admin" tree={[...]} cacheNode={{lazyData:null, ...}} segmentPath={[...]}>
        <AdminPage>
          <main className="container ...">
            <h1>
            <Card>
              <div className="rounded-lg...">
                <div>
                <CardContent>
                  <div className="p-6 pt-0">
                    ...
                      <_c>
                        <div className="relative w...">
                          <table ref={null} className="w-full cap...">
                            <_c2>
                            <_c4>
                              <tbody ref={null} className={"[&_tr:la..."}>
                                <_c8>
>                                 <tr
>                                   ref={null}
>                                   className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-m..."
>                                 >
                                    <_c12>
                                    <_c12>
                                    <_c12>
>                                   {" "}
                                    ...
                                ...
        ...

    at createUnhandledError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at beginWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:7833:211)
    at runWithFiberInDEV (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10168:97)
    at workLoopConcurrentByScheduler (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at tr (<anonymous>)
    at _c8 (http://localhost:9002/_next/static/chunks/src_fc8285cd._.js:75:449)
    at http://localhost:9002/_next/static/chunks/src_fc8285cd._.js:2092:262
    at Array.map (<anonymous>)
    at ProductTable (http://localhost:9002/_next/static/chunks/src_fc8285cd._.js:2092:45)
    at AdminPage (rsc://React/Server/C:%5CBill%20Management%20System%5CBill-Management-system%5C.next%5Cserver%5Cchunks%5Cssr%5C%5Broot%20of%20the%20server%5D__b8e6ef4f._.js?12:649:286)

this is second error can you please review this and fix all the issue i share dont give me error