i get 3 error first is
Error: In HTML, whitespace text nodes cannot be a child of <html>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
>                     <html lang="en" suppressHydrationWarning={true}>
>                       {" "}
                        ...
                    ...
        ...

    at createUnhandledError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at beginWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:7833:211)
    at runWithFiberInDEV (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10168:97)
    at workLoopConcurrentByScheduler (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at html (<anonymous>)
    at RootLayout (rsc://React/Server/C:%5CBill%20Management%20System%5CBill-Management-system%5C.next%5Cserver%5Cchunks%5Cssr%5C%5Broot%20of%20the%20server%5D__c19c728f._.js?2:126:263)

second is
Error: In HTML, whitespace text nodes cannot be a child of <html>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/admin" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
>                     <html lang="en" suppressHydrationWarning={true}>
>                       {" "}
                        ...
                    ...
        ...

    at createUnhandledError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at beginWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:7833:211)
    at runWithFiberInDEV (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10168:97)
    at workLoopConcurrentByScheduler (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at html (<anonymous>)
    at RootLayout (rsc://React/Server/C:%5CBill%20Management%20System%5CBill-Management-system%5C.next%5Cserver%5Cchunks%5Cssr%5C%5Broot%20of%20the%20server%5D__c19c728f._.js?2:126:263)

3rd is
Error: In HTML, whitespace text nodes cannot be a child of <tr>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <RedirectErrorBoundary router={{...}}>
      <InnerLayoutRouter url="/admin" tree={[...]} cacheNode={{lazyData:null, ...}} segmentPath={[...]}>
        <AdminPage>
          <main className="container ...">
            <h1>
            <Card>
              <div className="rounded-lg...">
                <div>
                <CardContent>
                  <div className="p-6 pt-0">
                    ...
                      <_c>
                        <div className="relative w...">
                          <table ref={null} className="w-full cap...">
                            <_c2>
                            <_c4>
                              <tbody ref={null} className={"[&_tr:la..."}>
                                <_c8>
>                                 <tr
>                                   ref={null}
>                                   className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-m..."
>                                 >
                                    <_c12>
                                    <_c12>
                                    <_c12>
>                                   {" "}
                                    ...
                                ...
        ...

    at createUnhandledError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (http://localhost:9002/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at beginWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:7833:211)
    at runWithFiberInDEV (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at performUnitOfWork (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10168:97)
    at workLoopConcurrentByScheduler (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (http://localhost:9002/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at tr (<anonymous>)
    at _c8 (http://localhost:9002/_next/static/chunks/src_480e4c33._.js:75:449)
    at http://localhost:9002/_next/static/chunks/src_480e4c33._.js:1887:262
    at Array.map (<anonymous>)
    at ProductTable (http://localhost:9002/_next/static/chunks/src_480e4c33._.js:1887:45)
    at AdminPage (rsc://React/Server/C:%5CBill%20Management%20System%5CBill-Management-system%5C.next%5Cserver%5Cchunks%5Cssr%5C%5Broot%20of%20the%20server%5D__b8e6ef4f._.js?12:647:286)